# site settings
title: Emanuel Pali
subtitle: Berg- und Skiführer
email: info@bergführer-pali.at
description: Ich zeige dir die schönsten Gipfel.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.bergfuehrer-pali.at" # the base hostname & protocol for your site
author: Emanuel Pali
street_address: Zillertal
city: Stumm
state: Tirol
zip_code: 6275
country: Österreich
phone: +43 664 3769941

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/bergfuehrer_pali
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/emanuel.pali.5
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
